#!/usr/local/bin/fish

set -l cmd

if test (count $argv) -eq 0
  set -l directory (pwd)
  set cmd " cd $directory"
else
  if test -d $argv[1]
    set cmd " cd $argv[1]"
  else if test -d "$HOME/$argv[1]"
    set cmd " cd $HOME/$argv[1]"
  else if contains $argv[1] (functions)
    set cmd " $argv[1]"
  else
    set cmd " cd (autojump $argv[1])"
  end
end

set -U NEW_SESSION_CMD $cmd

osascript -e "tell application \"iTerm\"" \
          -e "tell the current terminal to launch session \"Railscasts\"" \
          -e "end tell" > /dev/null ^/dev/null

history --delete -contains "tab"
history --delete -prefix "tab"
